apiVersion: apps/v1
kind: Deployment
metadata:
  name: "sampleapp1-82240947"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "sampleapp1-82240947"
  template:
    metadata:
      labels:
        app: "sampleapp1-82240947"
    spec:
      containers:
        - name: "sampleapp1-82240947"
          image: cepgbaseacr.azurecr.io/sampleapp1:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-db-secret
                  key: password
          volumeMounts:
            - mountPath: /mnt/cloud-sample
              name: sampleapp1-volume
              readOnly: false
              subPath: cloud-sample
            - mountPath: /config
              name: application-properties
              readOnly: true
              
      volumes:
        - name: sampleapp1-volume
          persistentVolumeClaim:
            claimName: cepg-aa-std-pvc
        - name: application-properties
          configMap:
            name: sampleapp1-configmap
            items:
              - key: application.yml
                path: application.yml
            defaultMode: 420

