apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - pvc.yaml
configMapGenerator:
  - files:
    - application.yml
    name: "sampleapp1-82240947-configmap"
patchesStrategicMerge:
  - deployment.yaml
  - ingress.yaml
