apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - pvc.yaml
configMapGenerator:
  - name: sampleapp1-82240947-configmap
    files:
      - application.yml
patchesStrategicMerge:
  - deployment.yaml
  - ingress.yaml

